"""a7 signals

Revision ID: 0806ce637fb8
Revises: 88c1d3c220b0
Create Date: 2026-08-08 02:27:13.508843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0806ce637fb8'
down_revision: Union[str, Sequence[str], None] = '88c1d3c220b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('profile', sa.String(length=24), nullable=False),
    sa.Column('stance', sa.String(length=12), nullable=False),
    sa.Column('conviction', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('horizon', sa.String(length=16), nullable=True),
    sa.Column('entry_low', sa.Float(), nullable=True),
    sa.Column('entry_high', sa.Float(), nullable=True),
    sa.Column('target_low', sa.Float(), nullable=True),
    sa.Column('target_high', sa.Float(), nullable=True),
    sa.Column('invalidation', sa.Float(), nullable=True),
    sa.Column('size_pct', sa.Float(), nullable=True),
    sa.Column('thesis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_verdict', sa.String(length=12), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_as_of'), 'signals', ['as_of'], unique=False)
    op.create_index(op.f('ix_signals_observed_at'), 'signals', ['observed_at'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_index('ix_signals_symbol_asof', 'signals', ['symbol', 'as_of'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signals_symbol_asof', table_name='signals')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_observed_at'), table_name='signals')
    op.drop_index(op.f('ix_signals_as_of'), table_name='signals')
    op.drop_table('signals')
    # ### end Alembic commands ###
