"""phase1 initial schema

Revision ID: 0e93b141291a
Revises: 
Create Date: 2026-08-05 00:04:40.840151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e93b141291a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('agent', sa.String(length=48), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent'), 'agent_runs', ['agent'], unique=False)
    op.create_table('consumer_offsets',
    sa.Column('consumer', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('last_acked_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('consumer', 'topic')
    )
    op.create_table('dead_letters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('consumer', sa.String(length=64), nullable=False),
    sa.Column('outbox_id', sa.BigInteger(), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letters_consumer'), 'dead_letters', ['consumer'], unique=False)
    op.create_table('feed_state',
    sa.Column('feed', sa.String(length=48), nullable=False),
    sa.Column('priority', sa.String(length=4), nullable=False),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=32), nullable=True),
    sa.Column('entries_seen', sa.BigInteger(), nullable=False),
    sa.Column('entries_new', sa.BigInteger(), nullable=False),
    sa.Column('consecutive_errors', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('feed')
    )
    op.create_table('holidays',
    sa.Column('day', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('segment', sa.String(length=8), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('day', 'segment')
    )
    op.create_index(op.f('ix_holidays_observed_at'), 'holidays', ['observed_at'], unique=False)
    op.create_table('http_audit',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('budget_tokens', sa.Float(), nullable=True),
    sa.Column('breaker_open', sa.Boolean(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_http_audit_observed_at'), 'http_audit', ['observed_at'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_created_at'), 'outbox', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_topic'), 'outbox', ['topic'], unique=False)
    op.create_table('securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('company_name', sa.Text(), nullable=False),
    sa.Column('series', sa.String(length=8), nullable=True),
    sa.Column('is_sme', sa.Boolean(), nullable=False),
    sa.Column('listing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('face_value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin'),
    sa.UniqueConstraint('symbol', 'series', name='uq_symbol_series')
    )
    op.create_index(op.f('ix_securities_observed_at'), 'securities', ['observed_at'], unique=False)
    op.create_index(op.f('ix_securities_symbol'), 'securities', ['symbol'], unique=False)
    op.create_table('filings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('feed', sa.String(length=48), nullable=False),
    sa.Column('dedup_key', sa.String(length=256), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.Text(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', name='uq_filing_content_hash')
    )
    op.create_index(op.f('ix_filings_event_at'), 'filings', ['event_at'], unique=False)
    op.create_index(op.f('ix_filings_feed'), 'filings', ['feed'], unique=False)
    op.create_index('ix_filings_feed_event_at', 'filings', ['feed', 'event_at'], unique=False)
    op.create_index(op.f('ix_filings_observed_at'), 'filings', ['observed_at'], unique=False)
    op.create_index(op.f('ix_filings_security_id'), 'filings', ['security_id'], unique=False)
    op.create_index(op.f('ix_filings_symbol'), 'filings', ['symbol'], unique=False)
    op.create_index('uq_filing_dedup_key', 'filings', ['feed', 'dedup_key'], unique=True, postgresql_where=sa.text('dedup_key IS NOT NULL'))
    op.create_table('security_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=64), nullable=False),
    sa.Column('alias_type', sa.String(length=16), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias', 'alias_type', 'security_id', name='uq_alias')
    )
    op.create_index(op.f('ix_security_aliases_alias'), 'security_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_security_aliases_observed_at'), 'security_aliases', ['observed_at'], unique=False)
    op.create_index(op.f('ix_security_aliases_security_id'), 'security_aliases', ['security_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('filing_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('fetch_status', sa.String(length=16), nullable=False),
    sa.Column('fetch_error', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_filing_id'), 'documents', ['filing_id'], unique=False)
    op.create_index(op.f('ix_documents_observed_at'), 'documents', ['observed_at'], unique=False)
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_observed_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_filing_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_security_aliases_security_id'), table_name='security_aliases')
    op.drop_index(op.f('ix_security_aliases_observed_at'), table_name='security_aliases')
    op.drop_index(op.f('ix_security_aliases_alias'), table_name='security_aliases')
    op.drop_table('security_aliases')
    op.drop_index('uq_filing_dedup_key', table_name='filings', postgresql_where=sa.text('dedup_key IS NOT NULL'))
    op.drop_index(op.f('ix_filings_symbol'), table_name='filings')
    op.drop_index(op.f('ix_filings_security_id'), table_name='filings')
    op.drop_index(op.f('ix_filings_observed_at'), table_name='filings')
    op.drop_index('ix_filings_feed_event_at', table_name='filings')
    op.drop_index(op.f('ix_filings_feed'), table_name='filings')
    op.drop_index(op.f('ix_filings_event_at'), table_name='filings')
    op.drop_table('filings')
    op.drop_index(op.f('ix_securities_symbol'), table_name='securities')
    op.drop_index(op.f('ix_securities_observed_at'), table_name='securities')
    op.drop_table('securities')
    op.drop_index(op.f('ix_outbox_topic'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_created_at'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_http_audit_observed_at'), table_name='http_audit')
    op.drop_table('http_audit')
    op.drop_index(op.f('ix_holidays_observed_at'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_table('feed_state')
    op.drop_index(op.f('ix_dead_letters_consumer'), table_name='dead_letters')
    op.drop_table('dead_letters')
    op.drop_table('consumer_offsets')
    op.drop_index(op.f('ix_agent_runs_agent'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
