"""a2 filing_classifications

Revision ID: 74e3802f0057
Revises: e657f5189698
Create Date: 2026-08-07 21:29:01.453003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74e3802f0057'
down_revision: Union[str, Sequence[str], None] = 'e657f5189698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filing_classifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('filing_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('materiality', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('routine', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('engine', sa.String(length=16), nullable=False),
    sa.Column('rule_trace', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id', 'model_version', name='uq_classification_version')
    )
    op.create_index(op.f('ix_filing_classifications_category'), 'filing_classifications', ['category'], unique=False)
    op.create_index(op.f('ix_filing_classifications_filing_id'), 'filing_classifications', ['filing_id'], unique=False)
    op.create_index(op.f('ix_filing_classifications_observed_at'), 'filing_classifications', ['observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filing_classifications_observed_at'), table_name='filing_classifications')
    op.drop_index(op.f('ix_filing_classifications_filing_id'), table_name='filing_classifications')
    op.drop_index(op.f('ix_filing_classifications_category'), table_name='filing_classifications')
    op.drop_table('filing_classifications')
    # ### end Alembic commands ###
