"""a5 flow tables

Revision ID: 88c1d3c220b0
Revises: dd48a0981f48
Create Date: 2026-08-08 01:35:44.244369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c1d3c220b0'
down_revision: Union[str, Sequence[str], None] = 'dd48a0981f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('large_deals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('day', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('client', sa.Text(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'symbol', 'client', 'side', 'qty', 'kind', name='uq_large_deal')
    )
    op.create_index(op.f('ix_large_deals_day'), 'large_deals', ['day'], unique=False)
    op.create_index(op.f('ix_large_deals_observed_at'), 'large_deals', ['observed_at'], unique=False)
    op.create_index(op.f('ix_large_deals_symbol'), 'large_deals', ['symbol'], unique=False)
    op.create_table('market_flow',
    sa.Column('day', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=8), nullable=False),
    sa.Column('buy_value', sa.Float(), nullable=True),
    sa.Column('sell_value', sa.Float(), nullable=True),
    sa.Column('net_value', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('day', 'category')
    )
    op.create_index(op.f('ix_market_flow_observed_at'), 'market_flow', ['observed_at'], unique=False)
    op.create_table('surveillance',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('framework', sa.String(length=8), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('as_of', 'symbol', 'framework', name='uq_surv')
    )
    op.create_index(op.f('ix_surveillance_as_of'), 'surveillance', ['as_of'], unique=False)
    op.create_index(op.f('ix_surveillance_observed_at'), 'surveillance', ['observed_at'], unique=False)
    op.create_index(op.f('ix_surveillance_symbol'), 'surveillance', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surveillance_symbol'), table_name='surveillance')
    op.drop_index(op.f('ix_surveillance_observed_at'), table_name='surveillance')
    op.drop_index(op.f('ix_surveillance_as_of'), table_name='surveillance')
    op.drop_table('surveillance')
    op.drop_index(op.f('ix_market_flow_observed_at'), table_name='market_flow')
    op.drop_table('market_flow')
    op.drop_index(op.f('ix_large_deals_symbol'), table_name='large_deals')
    op.drop_index(op.f('ix_large_deals_observed_at'), table_name='large_deals')
    op.drop_index(op.f('ix_large_deals_day'), table_name='large_deals')
    op.drop_table('large_deals')
    # ### end Alembic commands ###
