"""p5 performance + alerts

Revision ID: c8e345c6b50e
Revises: 0806ce637fb8
Create Date: 2026-08-08 10:53:55.055955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8e345c6b50e'
down_revision: Union[str, Sequence[str], None] = '0806ce637fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('evidence_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_observed_at'), 'alerts', ['observed_at'], unique=False)
    op.create_index(op.f('ix_alerts_symbol'), 'alerts', ['symbol'], unique=False)
    op.create_table('signal_performance',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('signal_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('stance', sa.String(length=12), nullable=False),
    sa.Column('profile', sa.String(length=24), nullable=False),
    sa.Column('conviction', sa.Float(), nullable=False),
    sa.Column('window', sa.String(length=8), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('ret', sa.Float(), nullable=False),
    sa.Column('index_ret', sa.Float(), nullable=True),
    sa.Column('excess', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', 'window', name='uq_perf_signal_window')
    )
    op.create_index(op.f('ix_signal_performance_observed_at'), 'signal_performance', ['observed_at'], unique=False)
    op.create_index(op.f('ix_signal_performance_signal_id'), 'signal_performance', ['signal_id'], unique=False)
    op.create_index(op.f('ix_signal_performance_symbol'), 'signal_performance', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signal_performance_symbol'), table_name='signal_performance')
    op.drop_index(op.f('ix_signal_performance_signal_id'), table_name='signal_performance')
    op.drop_index(op.f('ix_signal_performance_observed_at'), table_name='signal_performance')
    op.drop_table('signal_performance')
    op.drop_index(op.f('ix_alerts_symbol'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_observed_at'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
