"""phase3 prices financials scores

Revision ID: dd48a0981f48
Revises: 74e3802f0057
Create Date: 2026-08-08 01:12:20.819798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd48a0981f48'
down_revision: Union[str, Sequence[str], None] = '74e3802f0057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_daily',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('trade_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('series', sa.String(length=8), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('prev_close', sa.Float(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.Column('trades', sa.Float(), nullable=True),
    sa.Column('delivery_qty', sa.Float(), nullable=True),
    sa.Column('delivery_pct', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'trade_date', name='uq_price_symbol_date')
    )
    op.create_index(op.f('ix_price_daily_observed_at'), 'price_daily', ['observed_at'], unique=False)
    op.create_index('ix_price_security_date', 'price_daily', ['security_id', 'trade_date'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('agent', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_agent'), 'scores', ['agent'], unique=False)
    op.create_index('ix_scores_agent_symbol_asof', 'scores', ['agent', 'symbol', 'as_of'], unique=False)
    op.create_index(op.f('ix_scores_as_of'), 'scores', ['as_of'], unique=False)
    op.create_index(op.f('ix_scores_observed_at'), 'scores', ['observed_at'], unique=False)
    op.create_index(op.f('ix_scores_symbol'), 'scores', ['symbol'], unique=False)
    op.create_table('financials_quarterly',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('filing_id', sa.BigInteger(), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('basis', sa.String(length=16), nullable=False),
    sa.Column('audited', sa.Boolean(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('other_income', sa.Float(), nullable=True),
    sa.Column('total_income', sa.Float(), nullable=True),
    sa.Column('expenses', sa.Float(), nullable=True),
    sa.Column('finance_costs', sa.Float(), nullable=True),
    sa.Column('depreciation', sa.Float(), nullable=True),
    sa.Column('pbt', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('pat', sa.Float(), nullable=True),
    sa.Column('eps_basic', sa.Float(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'period_end', 'basis', name='uq_fin_symbol_period_basis')
    )
    op.create_index(op.f('ix_financials_quarterly_observed_at'), 'financials_quarterly', ['observed_at'], unique=False)
    op.create_index(op.f('ix_financials_quarterly_security_id'), 'financials_quarterly', ['security_id'], unique=False)
    op.create_index(op.f('ix_financials_quarterly_symbol'), 'financials_quarterly', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financials_quarterly_symbol'), table_name='financials_quarterly')
    op.drop_index(op.f('ix_financials_quarterly_security_id'), table_name='financials_quarterly')
    op.drop_index(op.f('ix_financials_quarterly_observed_at'), table_name='financials_quarterly')
    op.drop_table('financials_quarterly')
    op.drop_index(op.f('ix_scores_symbol'), table_name='scores')
    op.drop_index(op.f('ix_scores_observed_at'), table_name='scores')
    op.drop_index(op.f('ix_scores_as_of'), table_name='scores')
    op.drop_index('ix_scores_agent_symbol_asof', table_name='scores')
    op.drop_index(op.f('ix_scores_agent'), table_name='scores')
    op.drop_table('scores')
    op.drop_index('ix_price_security_date', table_name='price_daily')
    op.drop_index(op.f('ix_price_daily_observed_at'), table_name='price_daily')
    op.drop_table('price_daily')
    # ### end Alembic commands ###
