"""documents retry ladder for eventually-consistent archives

Revision ID: e657f5189698
Revises: 0e93b141291a
Create Date: 2026-08-05 11:58:59.469552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e657f5189698'
down_revision: Union[str, Sequence[str], None] = '0e93b141291a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('documents', sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'next_attempt_at')
    op.drop_column('documents', 'attempts')
    # ### end Alembic commands ###
